#!/bin/sh
f="$1"
base=$(basename $f)
top=`pwd`
mkdir -p failures
if [ ! -e $base.delta ]; then
	echo $f
	if ! pristine-tar gendelta $f $base.delta; then
		cp $f failures
	else
		mkdir workdir.$$
		tar xf $f -C workdir.$$
		cd workdir.$$
		if [ $(ls -1 | wc -l) = 1 ]; then
			cd * >/dev/null 2>&1
		fi
		if ! pristine-tar gentar $top/$base.delta $top/$base; then
			cd $top
			cp $f failures
		else
			cd $top
			if ! cmp $base $f; then
				cp $f failures
			fi
		fi
	fi
	rm -f $base
	rm -rf workdir.$$
fi
